# Generated by Django 2.0.3 on 2020-05-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='reg_toppings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Reg_extras', to='orders.Toppings'),
            preserve_default=False,
        ),
    ]
