# Generated by Django 2.2.10 on 2020-05-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
    ]
