# Generated by Django 2.2.10 on 2020-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200519_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='reg_toppings', to='orders.Toppings', verbose_name='Toppings'),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='Sic_toppings', to='orders.Toppings', verbose_name='Toppings'),
        ),
        migrations.AlterField(
            model_name='subs',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='sub_extra', to='orders.Extras', verbose_name='Extras'),
        ),
    ]
