# Generated by Django 2.0.3 on 2020-05-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizza_reg_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='sic_toppings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Sic_extras', to='orders.Toppings'),
        ),
    ]
